import './style.css';
import { ALL_ITEM_NAMES, BLUEPRINTS, CATEGORY, ITEM_SPAWN_CONFIG, JUNK_ITEMS, NPC_DIFFICULTY, OBSTACLES, SUBSTITUTE_ITEMS, WORLD } from './data.js';
import { createVehicle, generateInitialItems, getBestGarageVehicle, normalizeDifficulty, queueRespawn, scoreVehicle, updateRespawns } from './logic.js';

const app=document.querySelector('#app');
const savedDifficulty=()=>normalizeDifficulty(localStorage.getItem('grbDifficulty'));
const state={screen:'title',selectedDifficulty:savedDifficulty(),sound:localStorage.getItem('grbSound')!=='off',game:null,raf:0,last:0,selectedVehicleId:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function difficultyCards(){return Object.entries(NPC_DIFFICULTY).map(([key,d])=>`<button class="difficulty-card ${state.selectedDifficulty===key?'selected':''}" data-action="difficulty" data-value="${key}" aria-pressed="${state.selectedDifficulty===key}"><span class="check">✓</span><strong>${d.label}</strong><small>${d.caption}</small></button>`).join('');}
function showTitle(){
  state.screen='title';stopLoop(); const high=Number(localStorage.getItem('grbHighScore')||0);
  app.innerHTML=`<main class="title-screen"><div class="scanlines"></div><div class="gear gear-a">⚙</div><div class="gear gear-b">⚙</div><div class="sparks">${'<i></i>'.repeat(9)}</div><section class="hero-panel"><div class="serial">SCRAP WORKS // UNIT-09</div><h1>ガラクタ・ルンバ<br><span>ビルダーズ</span></h1><p class="subtitle">吸って、組んで、最強のガラクタを作れ！</p><div class="high-score"><small>🏆 HIGH SCORE</small><b>${high.toLocaleString()} 点</b></div><div class="difficulty-grid" aria-label="NPC難易度">${difficultyCards()}</div><button class="start-button" data-action="start"><span>GAME START</span></button><div class="title-options"><button data-action="sound" class="sound-button">効果音 ${state.sound?'ON':'OFF'}</button><div class="controls-card"><b>OPERATION</b><span>WASD / 矢印：移動</span><span>接近：通常吸引</span><span>P / Esc：一時停止</span></div></div></section></main>`;
}
function makeActor(x,y,type){return {x,y,type,r:24,angle:0,inventory:[],garage:[],buildCooldown:0,suction:null};}
function newGame(){
  const game={phase:'playing',paused:false,difficulty:state.selectedDifficulty,time:WORLD.roundSeconds,items:[],obstacles:OBSTACLES.map(x=>({...x})),player:makeActor(100,WORLD.height/2,'player'),npc:makeActor(WORLD.width-100,WORLD.height/2,'npc'),respawnQueue:[],nextItemId:0,nextVehicleId:0,initialItemCount:40,maxStageItems:40,npcThink:0,npcTargetId:null,npcAvoid:null,npcStill:0,npcLast:{x:0,y:0},keys:new Set(),effects:[]};
  game.npcLast={x:game.npc.x,y:game.npc.y}; generateInitialItems(game); state.game=game; state.selectedVehicleId=null; return game;
}
function showGame(){
  state.screen='game';const d=NPC_DIFFICULTY[state.game.difficulty];
  app.innerHTML=`<main class="game-shell"><header class="hud"><div class="best you"><small>YOU BEST</small><b id="youBest">未生成 / 0点</b></div><div class="best npc"><small>NPC BEST</small><b id="npcBest">未生成 / 0点</b></div><div class="hud-stat"><small>DIFFICULTY</small><b>${d.label}</b></div><div class="hud-stat"><small>TIME</small><b id="time">90</b></div><div class="hud-stat"><small>COLLECT</small><b id="counts">0 : 0</b></div><div class="hud-stat"><small>BUILT</small><b id="built">0 : 0</b></div></header><div class="canvas-wrap"><canvas id="gameCanvas"></canvas><div id="pausePanel" class="pause-panel hidden"><h2>PAUSED</h2><p>WASD / 矢印：移動　接近：通常吸引</p><button data-action="resume">再開</button><button data-action="quit">タイトルへ</button></div></div><footer>接近して通常吸引　<span>P / Esc：一時停止</span></footer></main>`;
  setupCanvas();startLoop();
}
let canvas,ctx,dpr=1;
function setupCanvas(){canvas=document.querySelector('#gameCanvas');ctx=canvas.getContext('2d');const resize=()=>{if(!canvas)return;dpr=Math.min(devicePixelRatio||1,2);const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);};resize();window.addEventListener('resize',resize,{once:true});}
function startLoop(){stopLoop();state.last=performance.now();state.raf=requestAnimationFrame(loop);}
function stopLoop(){if(state.raf)cancelAnimationFrame(state.raf);state.raf=0;}
function loop(now){if(state.screen!=='game')return;const dt=Math.min(.05,(now-state.last)/1000);state.last=now;update(dt);draw();state.raf=requestAnimationFrame(loop);}

function blocked(x,y,r){return x-r<0||x+r>WORLD.width||y-r<0||y+r>WORLD.height||state.game.obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);}
function moveActor(a,vx,vy,dt){if(!vx&&!vy)return false;const speed=Math.max(Math.abs(vx),Math.abs(vy)),len=Math.hypot(vx,vy)||1;vx=vx/len*speed;vy=vy/len*speed;a.angle=Math.atan2(vy,vx);const nx=a.x+vx*dt,ny=a.y+vy*dt;let moved=false;if(!blocked(nx,a.y,a.r)){a.x=nx;moved=true;}if(!blocked(a.x,ny,a.r)){a.y=ny;moved=true;}return moved;}
function update(dt){const g=state.game;if(g.paused)return;g.time-=dt;if(g.time<=0){g.time=0;endRound();return;}g.player.buildCooldown=Math.max(0,g.player.buildCooldown-dt);g.npc.buildCooldown=Math.max(0,g.npc.buildCooldown-dt);
  let dx=0,dy=0;if(g.keys.has('arrowleft')||g.keys.has('a'))dx--;if(g.keys.has('arrowright')||g.keys.has('d'))dx++;if(g.keys.has('arrowup')||g.keys.has('w'))dy--;if(g.keys.has('arrowdown')||g.keys.has('s'))dy++;moveActor(g.player,dx*245,dy*245,dt);
  updateNpc(dt); updateSuction(g.player,dt);updateSuction(g.npc,dt);updateRespawns(g,dt).forEach(i=>g.effects.push({x:i.x,y:i.y,age:0,type:'spawn'}));
  g.items.forEach(i=>{i.spawnAge+=dt;i.collectLock=Math.max(0,i.collectLock-dt)});g.effects.forEach(e=>e.age+=dt);g.effects=g.effects.filter(e=>e.age<.65);updateHud();
}
function itemValue(name){return CATEGORY(name)==='regular'?100:CATEGORY(name)==='substitute'?62:18;}
function chooseNpcTarget(){const g=state.game,d=NPC_DIFFICULTY[g.difficulty];let candidates=g.items.filter(i=>i.collectLock<=0&&Math.hypot(i.x-g.npc.x,i.y-g.npc.y)<=d.sightRange);if(!candidates.length)return null;if(Math.random()<d.mistakeRate)return candidates[Math.floor(Math.random()*candidates.length)];return candidates.sort((a,b)=>((itemValue(b.name)+Math.random()*d.targetNoise)/(Math.hypot(b.x-g.npc.x,b.y-g.npc.y)+30))-((itemValue(a.name)+Math.random()*d.targetNoise)/(Math.hypot(a.x-g.npc.x,a.y-g.npc.y)+30)))[0];}
function updateNpc(dt){const g=state.game,n=g.npc,d=NPC_DIFFICULTY[g.difficulty];g.npcThink-=dt;let target=g.items.find(i=>i.id===g.npcTargetId);if(!target||g.npcThink<=0){target=chooseNpcTarget();g.npcTargetId=target?.id??null;g.npcThink=d.thinkMin+Math.random()*(d.thinkMax-d.thinkMin);}
  if(g.npcAvoid){g.npcAvoid.time-=dt;if(g.npcAvoid.time<=0)g.npcAvoid=null;}let tx=g.npcAvoid?.x??target?.x,ty=g.npcAvoid?.y??target?.y;if(tx==null)return;
  let vx=tx-n.x,vy=ty-n.y,dist=Math.hypot(vx,vy);if(dist<30&&!g.npcAvoid){g.npcThink=0;return;}const look=55;const fx=n.x+vx/(dist||1)*look,fy=n.y+vy/(dist||1)*look;const danger=g.obstacles.find(o=>fx>o.x-30&&fx<o.x+o.w+30&&fy>o.y-30&&fy<o.y+o.h+30);if(danger){const side=(n.y<danger.y+danger.h/2?-1:1);vy+=side*220*d.avoidance;vx+=(n.x<danger.x?-1:1)*70;}
  const vlen=Math.hypot(vx,vy)||1;const moved=moveActor(n,vx/vlen*d.speed,vy/vlen*d.speed,dt);const delta=Math.hypot(n.x-g.npcLast.x,n.y-g.npcLast.y);g.npcStill=delta<1?g.npcStill+dt:0;g.npcLast={x:n.x,y:n.y};if(!moved||g.npcStill>d.stuckTime){const angle=Math.atan2(vy,vx)+(Math.random()<.5?-1:1)*Math.PI/2;g.npcAvoid={x:clamp(n.x+Math.cos(angle)*130,40,WORLD.width-40),y:clamp(n.y+Math.sin(angle)*130,40,WORLD.height-40),time:.65};g.npcStill=0;}
  if(n.inventory.length>=d.buildAt&&n.buildCooldown<=0)buildVehicle(n);
}
function nearestCollectible(a){return state.game.items.filter(i=>i.collectLock<=0).map(i=>({i,d:Math.hypot(i.x-a.x,i.y-a.y)})).filter(x=>x.d<63).sort((x,y)=>x.d-y.d)[0]?.i;}
function updateSuction(a,dt){const item=nearestCollectible(a);if(!item){a.suction=null;return;}if(a.suction?.id!==item.id)a.suction={id:item.id,progress:0};a.suction.progress+=dt;item.suctionBy=a.type;item.suctionProgress=a.suction.progress/0.75;if(a.suction.progress>=.75){collectItem(a,item);a.suction=null;}}
function collectItem(a,item){const g=state.game,idx=g.items.findIndex(i=>i.id===item.id);if(idx<0)return;a.inventory.push(item.name);g.items.splice(idx,1);queueRespawn(g,item.name);beep(260);if(a.type==='player'&&a.inventory.length>=9&&a.buildCooldown<=0)buildVehicle(a);}
function buildVehicle(a){if(!a.inventory.length||a.buildCooldown>0)return;const take=a.inventory.splice(0,Math.min(a.inventory.length,9));const v=createVehicle(take,++state.game.nextVehicleId,a.type);a.garage.push(v);a.buildCooldown=a.type==='player'?3:2.5;beep(a.type==='player'?520:380);updateHud();}
function updateHud(){const g=state.game;if(!g)return;const fmt=actor=>{const b=getBestGarageVehicle(actor.garage);return b?`${b.vehicle.name} / ${BLUEPRINTS[b.vehicle.base].name} / ${b.scoreData.score}点`:'未生成 / 0点';};const set=(id,val)=>{const e=document.querySelector(id);if(e&&e.textContent!==String(val))e.textContent=val;};set('#youBest',fmt(g.player));set('#npcBest',fmt(g.npc));set('#time',Math.ceil(g.time));set('#counts',`${g.player.inventory.length} : ${g.npc.inventory.length}`);set('#built',`${g.player.garage.length} : ${g.npc.garage.length}`);}
function endRound(){const g=state.game;if(g.phase!=='playing')return;if(g.player.inventory.length)buildVehicle(g.player);if(g.npc.inventory.length)buildVehicle(g.npc);g.phase='select';g.respawnQueue=[];stopLoop();showGarage();}
function showGarage(){state.screen='garage';const garage=state.game.player.garage;app.innerHTML=`<main class="garage-screen"><h1>完成車を選択</h1><p>カードまたは「選択する」で1台を指定してください</p><div class="vehicle-grid">${garage.map(v=>{const s=scoreVehicle(v);return `<article class="vehicle-card" data-action="select-vehicle" data-id="${v.id}"><div class="vehicle-icon">${vehicleEmoji(v.base)}</div><h2>${escapeHtml(v.name)}</h2><b>${s.score}点</b><p>${BLUEPRINTS[v.base].name}設計図 / 完成度 ${Math.round(s.completion*100)}%</p><button data-action="select-vehicle" data-id="${v.id}">選択する</button></article>`}).join('')||'<p>回収できませんでした。</p>'}</div><button class="confirm-button" data-action="confirm-vehicle" disabled>この乗り物で勝負</button></main>`;}
function vehicleEmoji(base){return {car:'🚗',bicycle:'🚲',airplane:'✈️',helicopter:'🚁',train:'🚆'}[base]||'🔧';}
function showResult(){const v=state.game.player.garage.find(x=>x.id===state.selectedVehicleId);if(!v)return;const ps=scoreVehicle(v),nb=getBestGarageVehicle(state.game.npc.garage),ns=nb?.scoreData.score||0,win=ps.score>=ns;localStorage.setItem('grbHighScore',Math.max(ps.score,Number(localStorage.getItem('grbHighScore')||0)));state.screen='result';app.innerHTML=`<main class="result-screen"><div class="result-panel"><small>FINAL JUDGEMENT</small><h1>${win?'YOU WIN!':'NPC WIN'}</h1><div class="duel"><section><b>YOU</b><span>${vehicleEmoji(v.base)}</span><h2>${escapeHtml(v.name)}</h2><strong>${ps.score}点</strong></section><i>VS</i><section><b>NPC</b><span>${vehicleEmoji(nb?.vehicle.base)}</span><h2>${escapeHtml(nb?.vehicle.name||'未生成')}</h2><strong>${ns}点</strong></section></div><button class="start-button" data-action="restart">もう一度</button><button data-action="quit">タイトルへ</button></div></main>`;beep(win?700:180);}
function togglePause(force){if(state.screen!=='game')return;const g=state.game;g.paused=force??!g.paused;document.querySelector('#pausePanel')?.classList.toggle('hidden',!g.paused);}

app.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;if(action==='difficulty'){state.selectedDifficulty=normalizeDifficulty(el.dataset.value);localStorage.setItem('grbDifficulty',state.selectedDifficulty);showTitle();}else if(action==='sound'){state.sound=!state.sound;localStorage.setItem('grbSound',state.sound?'on':'off');showTitle();}else if(action==='start'||action==='restart'){newGame();showGame();}else if(action==='resume')togglePause(false);else if(action==='quit')showTitle();else if(action==='select-vehicle'){state.selectedVehicleId=Number(el.dataset.id);document.querySelectorAll('.vehicle-card').forEach(c=>c.classList.toggle('selected',Number(c.dataset.id)===state.selectedVehicleId));const b=document.querySelector('.confirm-button');if(b)b.disabled=false;}else if(action==='confirm-vehicle')showResult();});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if((k==='p'||k==='escape')&&state.screen==='game'){e.preventDefault();togglePause();return;}state.game?.keys.add(k);});window.addEventListener('keyup',e=>state.game?.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{if(state.screen==='game')togglePause(true);});
function beep(freq){if(!state.sound)return;try{const ac=new AudioContext(),o=ac.createOscillator(),gain=ac.createGain();o.frequency.value=freq;gain.gain.setValueAtTime(.035,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.08);o.connect(gain).connect(ac.destination);o.start();o.stop(ac.currentTime+.08);}catch{}}

function draw(){const g=state.game,rect=canvas.getBoundingClientRect(),sx=rect.width/WORLD.width,sy=rect.height/WORLD.height;ctx.setTransform(dpr*sx,0,0,dpr*sy,0,0);ctx.clearRect(0,0,WORLD.width,WORLD.height);drawWorld(g);}
function drawWorld(g){const grad=ctx.createLinearGradient(0,0,0,WORLD.height);grad.addColorStop(0,'#17222b');grad.addColorStop(1,'#0b1118');ctx.fillStyle=grad;ctx.fillRect(0,0,WORLD.width,WORLD.height);ctx.strokeStyle='#233541';ctx.lineWidth=1;for(let x=0;x<WORLD.width;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.height);ctx.stroke();}for(let y=0;y<WORLD.height;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.width,y);ctx.stroke();}g.obstacles.forEach(drawObstacle);const labels=selectVisibleLabels(g);g.items.forEach(i=>drawItem(ctx,i,labels.has(i.id)));g.effects.forEach(drawEffect);drawActor(g.player,'#35e9ff','YOU');drawActor(g.npc,'#ff7a42','NPC');}
function drawObstacle(o){ctx.fillStyle='#3c4850';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#788891';ctx.lineWidth=4;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.save();ctx.beginPath();ctx.rect(o.x,o.y,o.w,o.h);ctx.clip();ctx.strokeStyle='#e6a21a';ctx.lineWidth=9;for(let x=o.x-o.h;x<o.x+o.w;x+=30){ctx.beginPath();ctx.moveTo(x,o.y+o.h);ctx.lineTo(x+o.h,o.y);ctx.stroke();}ctx.restore();}
function selectVisibleLabels(g){return new Set(g.items.map(i=>({id:i.id,d:Math.min(Math.hypot(i.x-g.player.x,i.y-g.player.y),Math.hypot(i.x-g.npc.x,i.y-g.npc.y))})).filter(x=>x.d<260).sort((a,b)=>a.d-b.d).slice(0,14).map(x=>x.id));}
function drawActor(a,color,label){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);ctx.fillStyle='#151d23';ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,a.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(29,0);ctx.lineTo(15,-8);ctx.lineTo(15,8);ctx.fill();ctx.rotate(-a.angle);ctx.fillStyle='#061015';ctx.fillRect(-25,-42,50,16);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.strokeRect(-25,-42,50,16);ctx.fillStyle='#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(label,0,-30);ctx.restore();}
function shapeBase(item,fn){ctx.save();ctx.translate(item.x,item.y);const s=1+Math.max(0,.35-item.spawnAge)*1.2;ctx.scale(s,s);fn(ctx,item);ctx.restore();}
function drawItem(c,item,label=true){const fn=ITEM_DRAWERS[item.name]||drawUnknownItem;shapeBase(item,fn);if(item.suctionProgress>0){c.strokeStyle=item.suctionBy==='player'?'#35e9ff':'#ff7a42';c.lineWidth=4;c.beginPath();c.arc(item.x,item.y,27,-Math.PI/2,-Math.PI/2+Math.PI*2*clamp(item.suctionProgress,0,1));c.stroke();}if(label)drawItemLabel(c,item);}
function drawItemLabel(c,item){c.save();c.font=`bold ${Math.hypot(item.x-state.game.player.x,item.y-state.game.player.y)<120?15:13}px sans-serif`;const w=c.measureText(item.name).width+12,x=item.x-w/2,y=item.y+25;c.fillStyle='rgba(3,8,12,.82)';c.strokeStyle='rgba(255,255,255,.55)';c.lineWidth=2;c.beginPath();c.roundRect(x,y,w,21,5);c.fill();c.stroke();c.fillStyle='#fff';c.textAlign='center';c.textBaseline='middle';c.fillText(item.name,item.x,y+11);c.restore();}
const metal=(c)=>{c.fillStyle='#8fa2ad';c.strokeStyle='#18242b';c.lineWidth=3;};
export function drawTire(c){c.fillStyle='#151719';c.strokeStyle='#687680';c.lineWidth=3;c.beginPath();c.arc(0,0,18,0,7);c.fill();c.stroke();c.fillStyle='#8c9aa3';c.beginPath();c.arc(0,0,10,0,7);c.fill();c.stroke();c.fillStyle='#26343b';c.beginPath();c.arc(0,0,4,0,7);c.fill();}
function drawWheel(c){c.strokeStyle='#aebbc2';c.lineWidth=3;c.beginPath();c.arc(0,0,17,0,7);c.stroke();for(let a=0;a<6;a++){c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*16,Math.sin(a)*16);c.stroke();}c.fillStyle='#586973';c.beginPath();c.arc(0,0,4,0,7);c.fill();}
export function drawEngine(c){metal(c);c.fillRect(-17,-13,30,27);c.strokeRect(-17,-13,30,27);c.fillStyle='#52656e';for(let x=-12;x<12;x+=8)c.fillRect(x,-19,6,8);c.strokeStyle='#d27737';c.lineWidth=4;c.beginPath();c.moveTo(13,-7);c.quadraticCurveTo(24,-7,20,11);c.stroke();c.fillStyle='#e6b52c';c.beginPath();c.arc(-11,10,7,0,7);c.fill();}
export function drawSeat(c){c.fillStyle='#596974';c.strokeStyle='#1a252c';c.lineWidth=3;c.beginPath();c.roundRect(-14,-19,25,20,5);c.fill();c.stroke();c.beginPath();c.roundRect(-15,0,31,13,5);c.fill();c.stroke();}
function drawMotor(c){metal(c);c.beginPath();c.roundRect(-16,-12,29,24,8);c.fill();c.stroke();c.strokeStyle='#d5e5ec';c.lineWidth=3;c.beginPath();c.moveTo(13,0);c.lineTo(23,0);c.stroke();c.fillStyle='#20333e';c.font='bold 13px sans-serif';c.fillText('M',-9,5);}
export function drawWing(c){c.fillStyle='#a6bcc7';c.strokeStyle='#25343c';c.lineWidth=3;c.beginPath();c.moveTo(-25,8);c.lineTo(0,-14);c.lineTo(25,8);c.lineTo(4,5);c.lineTo(0,14);c.lineTo(-4,5);c.closePath();c.fill();c.stroke();}
export function drawFan(c){c.strokeStyle='#9eb0b8';c.lineWidth=3;c.beginPath();c.arc(0,0,19,0,7);c.stroke();c.fillStyle='#54a8b2';for(let a=0;a<4;a++){c.save();c.rotate(a*Math.PI/2);c.beginPath();c.ellipse(8,0,9,4,0,0,7);c.fill();c.restore();}c.fillStyle='#d2dde1';c.beginPath();c.arc(0,0,4,0,7);c.fill();}
export function drawFridge(c){c.fillStyle='#d3e4e8';c.strokeStyle='#263841';c.lineWidth=3;c.fillRect(-13,-20,26,40);c.strokeRect(-13,-20,26,40);c.beginPath();c.moveTo(-13,-4);c.lineTo(13,-4);c.stroke();c.strokeStyle='#546b75';c.lineWidth=2;c.beginPath();c.moveTo(7,-15);c.lineTo(7,-8);c.moveTo(7,2);c.lineTo(7,12);c.stroke();}
function drawUnknownItem(c){metal(c);c.fillRect(-15,-15,30,30);c.strokeRect(-15,-15,30,30);c.strokeStyle='#d59b27';c.beginPath();c.moveTo(-15,-15);c.lineTo(15,15);c.moveTo(15,-15);c.lineTo(-15,15);c.stroke();}
function simplePath(fill,path){return c=>{c.fillStyle=fill;c.strokeStyle='#202a30';c.lineWidth=3;c.beginPath();path(c);c.fill();c.stroke();};}
const rectShape=(color,w=32,h=25,detail)=>c=>{c.fillStyle=color;c.strokeStyle='#202a30';c.lineWidth=3;c.beginPath();c.roundRect(-w/2,-h/2,w,h,4);c.fill();c.stroke();detail?.(c);};
const circleShape=(color,detail)=>c=>{c.fillStyle=color;c.strokeStyle='#202a30';c.lineWidth=3;c.beginPath();c.arc(0,0,17,0,7);c.fill();c.stroke();detail?.(c);};
function drawDonut(c){c.fillStyle='#e881a7';c.strokeStyle='#522e37';c.lineWidth=3;c.beginPath();c.arc(0,0,17,0,7);c.fill();c.stroke();c.fillStyle='#182229';c.beginPath();c.arc(0,0,6,0,7);c.fill();for(let i=0;i<7;i++){c.strokeStyle=['#fff','#62dbef','#ffd75e'][i%3];c.beginPath();c.moveTo(Math.cos(i)*10,Math.sin(i)*10);c.lineTo(Math.cos(i)*13,Math.sin(i)*13);c.stroke();}}
function drawEffect(e){const p=e.age/.65;ctx.save();ctx.globalAlpha=1-p;ctx.strokeStyle='#ffe064';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,8+p*35,0,7);ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(e.x+Math.cos(a)*15,e.y+Math.sin(a)*15);ctx.lineTo(e.x+Math.cos(a)*(22+p*30),e.y+Math.sin(a)*(22+p*30));ctx.stroke();}ctx.restore();}
const ITEM_DRAWERS={
 'タイヤ':drawTire,'車輪':drawWheel,'エンジン':drawEngine,'モーター':drawMotor,'座席':drawSeat,
 'サドル':simplePath('#765344',c=>{c.moveTo(-16,5);c.quadraticCurveTo(0,-11,16,5);c.lineTo(10,11);c.lineTo(-11,11);c.closePath();}),
 'ハンドル':c=>{c.strokeStyle='#aab8bf';c.lineWidth=5;c.beginPath();c.arc(0,0,16,0,7);c.stroke();for(let a=0;a<3;a++){c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a*2.1)*14,Math.sin(a*2.1)*14);c.stroke();}},
 'ペダル':c=>{c.strokeStyle='#aab8bf';c.lineWidth=3;c.beginPath();c.moveTo(-12,-10);c.lineTo(12,10);c.stroke();c.strokeRect(-17,-14,9,6);c.strokeRect(8,8,9,6);c.beginPath();c.arc(0,0,5,0,7);c.stroke();},
 '車体':simplePath('#d65b3f',c=>{c.moveTo(-22,8);c.lineTo(-16,-5);c.lineTo(-7,-13);c.lineTo(11,-13);c.lineTo(20,-3);c.lineTo(23,8);c.closePath();}),
 'フレーム':c=>{c.strokeStyle='#55b7c8';c.lineWidth=5;c.beginPath();c.moveTo(-17,13);c.lineTo(0,-14);c.lineTo(15,13);c.closePath();c.moveTo(0,-14);c.lineTo(5,13);c.stroke();},
 '機体':simplePath('#a9bec8',c=>{c.moveTo(23,0);c.lineTo(5,-9);c.lineTo(-19,-7);c.lineTo(-23,0);c.lineTo(-19,7);c.lineTo(5,9);c.closePath();}),
 '主翼':drawWing,'尾翼':simplePath('#9fb5c0',c=>{c.moveTo(-17,8);c.lineTo(0,0);c.lineTo(7,-18);c.lineTo(13,5);c.lineTo(20,10);c.closePath();}),
 '操縦席':rectShape('#708995',30,25,c=>{c.fillStyle='#68d5ed';c.beginPath();c.roundRect(-9,-8,18,11,5);c.fill();}),
 'メインローター':c=>{c.fillStyle='#9eafb7';for(let a=0;a<4;a++){c.save();c.rotate(a*Math.PI/2);c.fillRect(0,-3,27,6);c.restore();}c.fillStyle='#344750';c.beginPath();c.arc(0,0,5,0,7);c.fill();},'テールローター':drawFan,
 '着陸脚':c=>{c.strokeStyle='#aebac0';c.lineWidth=4;c.beginPath();c.moveTo(-11,-12);c.lineTo(-15,12);c.lineTo(13,12);c.moveTo(10,-12);c.lineTo(15,12);c.stroke();},
 '車両ボディ':rectShape('#3b91ad',40,26,c=>{c.fillStyle='#b9e3eb';for(let x=-14;x<15;x+=10)c.fillRect(x,-7,7,9);}),
 '台車':rectShape('#59666d',35,13,c=>{c.fillStyle='#14191c';[-11,11].forEach(x=>{c.beginPath();c.arc(x,9,5,0,7);c.fill();});}),
 '運転席':rectShape('#d8a72b',31,31,c=>{c.fillStyle='#8ee2ed';c.fillRect(-10,-9,20,11);}),
 '連結器':c=>{c.strokeStyle='#aeb9be';c.lineWidth=6;c.beginPath();c.arc(-5,0,8,.6,5.7);c.lineTo(16,0);c.stroke();},
 'ドーナツ':drawDonut,'クッキー':circleShape('#a96d3f',c=>{c.fillStyle='#3f291f';[[-8,-6],[7,-9],[4,6],[-9,9]].forEach(p=>{c.beginPath();c.arc(...p,2.5,0,7);c.fill();});}),
 'フライパン':c=>{c.fillStyle='#343d42';c.strokeStyle='#8d9ca3';c.lineWidth=3;c.beginPath();c.arc(-6,0,14,0,7);c.fill();c.stroke();c.lineWidth=7;c.beginPath();c.moveTo(7,0);c.lineTo(25,0);c.stroke();},
 'ソファ':rectShape('#8d5aa3',37,25,c=>{c.strokeStyle='#432d4e';c.beginPath();c.moveTo(-12,-11);c.lineTo(-12,10);c.moveTo(12,-11);c.lineTo(12,10);c.stroke();}),
 '段ボール':rectShape('#b8864e',31,29,c=>{c.strokeStyle='#e5c28f';c.beginPath();c.moveTo(0,-14);c.lineTo(0,14);c.moveTo(-15,-7);c.lineTo(15,-7);c.stroke();}),
 '扇風機':drawFan,'スキー板':c=>{c.fillStyle='#4ab3d0';[-7,7].forEach(x=>{c.beginPath();c.roundRect(x-3,-22,6,44,3);c.fill();});},
 '竹とんぼ':c=>{c.strokeStyle='#a77d43';c.lineWidth=4;c.beginPath();c.moveTo(0,-3);c.lineTo(0,21);c.stroke();c.fillStyle='#d2a45d';c.beginPath();c.moveTo(-25,-5);c.lineTo(0,-11);c.lineTo(25,-5);c.lineTo(0,0);c.closePath();c.fill();},
 'ショッピングカート':c=>{c.strokeStyle='#aab8bd';c.lineWidth=3;c.strokeRect(-17,-13,30,21);c.beginPath();c.moveTo(13,-13);c.lineTo(21,-18);c.stroke();c.fillStyle='#20272b';[-11,10].forEach(x=>{c.beginPath();c.arc(x,14,4,0,7);c.fill();});},
 'スプーン':c=>{c.fillStyle='#c8d4d8';c.strokeStyle='#5d6b70';c.beginPath();c.ellipse(0,-11,9,12,0,0,7);c.fill();c.stroke();c.lineWidth=5;c.beginPath();c.moveTo(0,0);c.lineTo(0,23);c.stroke();},
 '植木鉢':c=>{c.fillStyle='#a9573b';c.fillRect(-12,0,24,17);c.fillStyle='#55a95a';[-9,0,9].forEach((x,i)=>{c.beginPath();c.ellipse(x,-9-i%2*4,7,12,x/18,0,7);c.fill();});},
 '掃除機':c=>{c.fillStyle='#d24f55';c.strokeStyle='#392d31';c.lineWidth=3;c.beginPath();c.roundRect(-16,-10,26,25,8);c.fill();c.stroke();c.beginPath();c.moveTo(9,-3);c.quadraticCurveTo(27,-15,23,9);c.stroke();c.strokeRect(17,8,12,6);},
 'ゲームコントローラー':simplePath('#596875',c=>{c.moveTo(-20,8);c.quadraticCurveTo(-17,-16,-5,-10);c.lineTo(5,-10);c.quadraticCurveTo(17,-16,20,8);c.quadraticCurveTo(15,18,7,8);c.lineTo(-7,8);c.quadraticCurveTo(-15,18,-20,8);}),
 '冷蔵庫':drawFridge,
 '長靴':simplePath('#547485',c=>{c.moveTo(-10,-20);c.lineTo(7,-20);c.lineTo(7,7);c.quadraticCurveTo(22,8,20,17);c.lineTo(-10,17);c.closePath();}),
 'バケツ':c=>{c.fillStyle='#708e9a';c.strokeStyle='#26383f';c.lineWidth=3;c.beginPath();c.moveTo(-14,-9);c.lineTo(-10,17);c.lineTo(10,17);c.lineTo(14,-9);c.closePath();c.fill();c.stroke();c.beginPath();c.arc(0,-7,17,Math.PI,0);c.stroke();},
 '枕':rectShape('#e4d6c6',34,25,c=>{c.strokeStyle='#a59b90';c.strokeRect(-10,-7,20,14);}),
 '傘':c=>{c.fillStyle='#c14c67';c.beginPath();c.arc(0,0,19,Math.PI,0);c.fill();c.strokeStyle='#bec8cc';c.lineWidth=3;c.beginPath();c.moveTo(0,0);c.lineTo(0,20);c.quadraticCurveTo(0,27,7,22);c.stroke();},
 '本':rectShape('#426fa1',30,34,c=>{c.strokeStyle='#e1d9bd';c.beginPath();c.moveTo(0,-16);c.lineTo(0,16);c.stroke();}),
 'ぬいぐるみ':c=>{c.fillStyle='#b77b4d';[[-10,-13],[10,-13]].forEach(p=>{c.beginPath();c.arc(...p,7,0,7);c.fill();});c.beginPath();c.arc(0,0,15,0,7);c.fill();c.fillStyle='#1d2428';c.beginPath();c.arc(-5,-3,2,0,7);c.arc(5,-3,2,0,7);c.fill();},
 'やかん':c=>{c.fillStyle='#aebcc2';c.strokeStyle='#34454d';c.lineWidth=3;c.beginPath();c.arc(0,4,15,0,7);c.fill();c.stroke();c.beginPath();c.arc(0,-1,18,Math.PI,0);c.stroke();c.beginPath();c.moveTo(13,0);c.lineTo(25,-7);c.lineTo(17,7);c.fill();},
 'テレビ':rectShape('#3f4d54',34,29,c=>{c.fillStyle='#7db2ba';c.fillRect(-11,-8,18,15);c.fillStyle='#cad4d7';c.beginPath();c.arc(12,-3,2,0,7);c.fill();}),
 'トイレットペーパー':c=>{c.fillStyle='#eeeae0';c.strokeStyle='#9ba0a0';c.lineWidth=3;c.beginPath();c.ellipse(0,0,17,20,0,0,7);c.fill();c.stroke();c.fillStyle='#8b7968';c.beginPath();c.ellipse(0,0,6,8,0,0,7);c.fill();},
 'サッカーボール':circleShape('#e9eceb',c=>{c.fillStyle='#263036';c.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5;c.lineTo(Math.cos(a)*7,Math.sin(a)*7);}c.closePath();c.fill();}),
};
export { ITEM_DRAWERS, drawItem, drawItemLabel, drawUnknownItem };

showTitle();
