import './style.css';import {CONFIG,VEHICLES,VEHICLE_ORDER,SUBSTITUTES,JUNK,SIZE,meta,slotList} from './data.js';import {buildVehicle,scoreVehicle,removeUsed,relation,findBestVehicle,addToInventory} from './logic.js';
const app=document.querySelector('#app'),debug=new URLSearchParams(location.search).get('debug')==='1';
let screen='title',target='car',sound=localStorage.getItem('grbSound')!=='off',audio=null,game=null,raf=0,keys=new Set(),last=0,uid=0;
const obstacles=[{x:270,y:100,w:85,h:45,c:'#8e6548',t:'机'},{x:510,y:90,w:60,h:90,c:'#7b563e',t:'箱'},{x:385,y:320,w:120,h:42,c:'#846044',t:'机'},{x:710,y:255,w:62,h:65,c:'#72513c',t:'箱'},{x:150,y:340,w:25,h:35,c:'#f07834',t:'△'},{x:820,y:110,w:25,h:35,c:'#f07834',t:'△'}];
function beep(kind){if(!sound||!audio)return;const map={collect:[650,.05],power:[180,.12],build:[330,.35],warn:[880,.12],win:[520,.5],lose:[130,.45]};const [f,d]=map[kind]||map.collect,o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type=kind==='build'?'square':'sine';g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function soundButton(){return `<button class="secondary sound" data-act="sound">🔊 ${sound?'ON':'OFF'}</button>`}
function title(){stop();screen='title';app.innerHTML=`${soundButton()}<main class="screen"><section class="panel center"><h1 class="title">ガラクタ・ルンバ<br>ビルダーズ</h1><p class="subtitle">吸って、組んで、ガラクタ対決！</p><button class="primary" data-act="start">ゲーム開始</button><div class="instructions"><b>操作方法</b><br>WASD / 矢印：移動　 Space長押し：強力吸引<br>E：乗り物生成　 Esc：一時停止</div><p>🏆 最高得点：<b>${localStorage.getItem('grbHigh')||0}</b> / 1000</p></section></main>`}
function select(){stop();screen='select';app.innerHTML=`${soundButton()}<main class="screen"><section class="panel"><h1>設計図を選択</h1><p>NPCも同じ目標を狙います。</p><div class="cards">${VEHICLE_ORDER.map(k=>{const v=VEHICLES[k];return `<button class="vcard ${k===target?'selected':''}" data-target="${k}"><div class="vicon">${v.icon}</div><h2>${v.name}</h2><div class="slots">${Object.entries(v.slots).map(([n,c])=>`${n} × ${c}`).join('<br>')}<br><b>計 ${slotList(k).length}個</b></div></button>`}).join('')}</div><div class="center"><button class="primary" data-act="round">ラウンド開始</button><button class="secondary" data-act="title">戻る</button></div></section></main>`}
function rnd(a,b){return a+Math.random()*(b-a)}function hitsRect(x,y,r,o){return x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h}function freePos(near){for(let z=0;z<100;z++){let x=near?rnd(near.x-100,near.x+100):rnd(35,925),y=near?rnd(near.y-100,near.y+100):rnd(45,495);if(x>25&&x<935&&y>30&&y<510&&!obstacles.some(o=>hitsRect(x,y,20,o)))return{x,y}}return{x:480,y:270}}
function makeItem(name,near){const m=meta(name),p=freePos(near);return{id:'i'+uid++,name,...m,...SIZE[m.size],x:p.x,y:p.y,vx:0,vy:0,progressP:0,progressN:0}}
function itemPool(){let names=[];const needed=slotList(target);for(let n=0;n<2;n++)names.push(...needed);while(names.length<22)names.push(needed[Math.floor(Math.random()*needed.length)]);const all=VEHICLE_ORDER.flatMap(slotList);while(names.length<42)names.push(all[Math.floor(Math.random()*all.length)]);const subs=Object.keys(SUBSTITUTES);while(names.length<62)names.push(subs[Math.floor(Math.random()*subs.length)]);while(names.length<80)names.push(JUNK[Math.floor(Math.random()*JUNK.length)]);return names.sort(()=>Math.random()-.5).map((n,i)=>makeItem(n,i<5?{x:100,y:270}:i<10?{x:860,y:270}:null))}
function startGame(){screen='game';keys.clear();const now=performance.now();game={time:CONFIG.ROUND,player:actor(90,270,'player'),npc:actor(870,270,'npc'),items:itemPool(),particles:[],message:'集めて作ろう！',messageT:1.5,paused:false,warn10:false,warn5:false,shake:0,buildCd:0,npcThink:0,fps:60};renderShell();last=now;cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function actor(x,y,type){return{x,y,r:27,type,angle:0,inventory:[],garage:[],power:false,target:null}}
function renderShell(){app.innerHTML=`<div class="game-shell"><div class="hud"><span>⏱ <b id="time">30.0</b>秒</span><span>目標 <b>${VEHICLES[target].icon} ${VEHICLES[target].name}</b></span><span>YOU <b id="pc">0 / 25</b>　完成 <b id="pg">0</b></span><span>NPC <b id="nc">0 / 25</b>　完成 <b id="ng">0</b></span></div><div class="stage-wrap"><canvas class="stage"></canvas><aside class="inventory"><h3>回収ボックス</h3><div id="inv"></div></aside><div class="message" id="msg"></div><div id="pause"></div></div><div class="bottom"><div class="build-hint" id="hint">E：生成</div><div class="garage" id="garage"></div><span>Space：強力吸引</span></div></div>`;const c=app.querySelector('canvas');c.width=CONFIG.W*devicePixelRatio;c.height=CONFIG.H*devicePixelRatio;c.getContext('2d').scale(devicePixelRatio,devicePixelRatio);game.canvas=c;game.ctx=c.getContext('2d')}
function stop(){cancelAnimationFrame(raf);raf=0;keys.clear();game=null}
function moveActor(a,dx,dy,speed,dt){const l=Math.hypot(dx,dy)||1,ox=a.x,oy=a.y;a.x+=dx/l*speed*dt;a.y+=dy/l*speed*dt;a.x=Math.max(a.r,Math.min(CONFIG.W-a.r,a.x));a.y=Math.max(a.r,Math.min(CONFIG.H-a.r,a.y));if(obstacles.some(o=>hitsRect(a.x,a.y,a.r,o))){a.x=ox;if(obstacles.some(o=>hitsRect(a.x,a.y,a.r,o)))a.y=oy}if(dx||dy)a.angle=Math.atan2(dy,dx)}
function suck(a,item,power,dt){const range=power?CONFIG.POWER_RANGE:CONFIG.NORMAL_RANGE,d=Math.hypot(item.x-a.x,item.y-a.y);if(d>range)return;const force=(power?260:80)*(1-d/range),ox=item.x,oy=item.y;item.x+=(a.x-item.x)/(d||1)*force*dt;item.y+=(a.y-item.y)/(d||1)*force*dt;if(obstacles.some(o=>hitsRect(item.x,item.y,item.r,o))){item.x=ox;item.y=oy}const key=a.type==='player'?'progressP':'progressN';if(d<a.r+item.r+9)item[key]+=dt*(power?2.1:1);else item[key]=Math.max(0,item[key]-dt*.4);if(item[key]>=item.time)collect(a,item)}
function collect(a,item){if(a.inventory.length>=CONFIG.CAPACITY){if(a.type==='player')say('回収ボックス満杯！');item.progressP=item.progressN=0;return}a.inventory=addToInventory(a.inventory,item,CONFIG.CAPACITY);game.items=game.items.filter(x=>x!==item);burst(item.x,item.y,item.color,6);if(a.type==='player'){beep('collect');say('部品を回収！',.35)}}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)game.particles.push({x,y,vx:rnd(-80,80),vy:rnd(-90,40),life:rnd(.3,.7),color})}
function say(s,t=1.1){if(!game)return;game.message=s;game.messageT=t}
function build(a){if(game.paused||game.buildCd>0)return;if(a.inventory.length<6){if(a.type==='player')say('生成には部品が6個必要です');return}const v=buildVehicle(a.inventory,target);if(!v)return;a.inventory=removeUsed(a.inventory,v.usedIds);a.garage.push(v);game.buildCd=.42;game.shake=.35;burst(a.x,a.y,'#fff',22);burst(a.x,a.y,'#ffdc62',12);beep('build');say(`${v.name}が完成！`,1.5)}
function npcAI(dt){const n=game.npc;n.npcThink-=dt;if(n.npcThink<=0||!n.target||!game.items.includes(n.target)){n.npcThink=rnd(.3,.65);n.target=[...game.items].sort((a,b)=>npcValue(b,n)-npcValue(a,n))[0]}if(n.inventory.length>=20||(game.time<=5&&n.inventory.length>=6)||readyForTarget(n.inventory))build(n);if(n.target){const wobble=Math.sin(performance.now()/430)*.22,dx=n.target.x-n.x,dy=n.target.y-n.y,d=Math.hypot(dx,dy);n.power=d<190&&game.items.filter(i=>Math.hypot(i.x-n.x,i.y-n.y)<190).length>=2;moveActor(n,dx+Math.cos(wobble)*24,dy+Math.sin(wobble)*24,185*(n.power?.55:1),dt)}}
function npcValue(i,n){const d=Math.hypot(i.x-n.x,i.y-n.y);let q=0;for(const s of slotList(target)){const r=relation(i,s);q=Math.max(q,r.value)}return q*3-d+rnd(0,50)}function readyForTarget(inv){const a=findBestVehicle(inv,target);return a.key===target&&a.assignments.filter(x=>x.type==='exact'||x.type==='common').length>=Math.min(7,slotList(target).length)}
function update(dt){if(game.paused)return;game.time=Math.max(0,game.time-dt);game.buildCd=Math.max(0,game.buildCd-dt);game.shake=Math.max(0,game.shake-dt);game.messageT=Math.max(0,game.messageT-dt);const p=game.player,dx=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft')),dy=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));p.power=keys.has(' ');moveActor(p,dx,dy,CONFIG.PLAYER_SPEED*(p.power?.55:1),dt);npcAI(dt);for(const i of [...game.items]){suck(p,i,p.power,dt);if(game.items.includes(i))suck(game.npc,i,game.npc.power,dt)}for(const q of game.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=110*dt;q.life-=dt}game.particles=game.particles.filter(q=>q.life>0);if(game.time<=10&&!game.warn10){game.warn10=true;beep('warn');say('残り10秒！')}if(game.time<=5&&!game.warn5){game.warn5=true;beep('warn');say('残り5秒！')}if(game.time<=0){if(game.npc.inventory.length>=6)build(game.npc);finalSelect();return}updateHud()}
function updateHud(){const g=game,p=g.player,n=g.npc;app.querySelector('#time').textContent=g.time.toFixed(1);app.querySelector('#pc').textContent=`${p.inventory.length} / 25`;app.querySelector('#nc').textContent=`${n.inventory.length} / 25`;app.querySelector('#pg').textContent=p.garage.length;app.querySelector('#ng').textContent=n.garage.length;const counts={};p.inventory.forEach(i=>counts[i.name]=(counts[i.name]||0)+1);app.querySelector('#inv').innerHTML=Object.entries(counts).map(([x,c])=>`<div class="item-row"><span>${x}</span><b>× ${c}</b></div>`).join('')||'空っぽ';app.querySelector('#hint').innerHTML=p.inventory.length>=6?'✅ E：生成可能':'🔒 あと '+(6-p.inventory.length)+'個';app.querySelector('#garage').innerHTML=p.garage.map(v=>`<div class="mini">${VEHICLES[v.base].icon} ${v.name}</div>`).join('');app.querySelector('#msg').textContent=g.messageT>0?g.message:''}
function loop(t){if(!game)return;let dt=Math.min(.033,(t-last)/1000);last=t;game.fps=game.fps*.9+(1/dt)*.1;update(dt);if(!game)return;draw();raf=requestAnimationFrame(loop)}
function draw(){const {ctx}=game;ctx.save();if(game.shake)ctx.translate(rnd(-5,5),rnd(-5,5));ctx.fillStyle='#556b48';ctx.fillRect(0,0,960,540);ctx.strokeStyle='#ffffff12';for(let x=0;x<960;x+=40)for(let y=0;y<540;y+=40)ctx.strokeRect(x,y,40,40);for(const o of obstacles){ctx.fillStyle=o.c;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText(o.t,o.x+5,o.y+17)}for(const i of game.items)drawItem(ctx,i);drawActor(ctx,game.player);drawActor(ctx,game.npc);for(const p of game.particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5)}ctx.globalAlpha=1;if(debug)drawDebug(ctx);ctx.restore()}
function drawItem(c,i){c.save();c.translate(i.x,i.y);c.fillStyle=i.color;c.strokeStyle='#18202b';c.lineWidth=3;if(['タイヤ','車輪','ドーナツ','クッキー'].includes(i.name)){c.beginPath();c.arc(0,0,i.r,0,7);c.fill();c.stroke();if(i.name!=='クッキー'){c.fillStyle='#556b48';c.beginPath();c.arc(0,0,i.r*.42,0,7);c.fill()}}else if(i.name==='主翼'||i.name==='尾翼'||i.name==='段ボール'||i.name==='スキー板'){c.fillRect(-i.r,-i.r*.35,i.r*2,i.r*.7)}else{c.fillRect(-i.r,-i.r,i.r*2,i.r*2);c.strokeRect(-i.r,-i.r,i.r*2,i.r*2)}c.fillStyle=i.name==='冷蔵庫'?'#222':'#fff';c.textAlign='center';c.font='bold 10px sans-serif';c.fillText(i.label,0,3);c.restore();const pr=Math.max(i.progressP,i.progressN)/i.time;if(pr>0){c.fillStyle='#222';c.fillRect(i.x-15,i.y-i.r-8,30,4);c.fillStyle='#ffdf55';c.fillRect(i.x-15,i.y-i.r-8,30*Math.min(1,pr),4)}}
function drawActor(c,a){const range=a.power?CONFIG.POWER_RANGE:CONFIG.NORMAL_RANGE;if(a.power||debug){c.fillStyle=a.type==='player'?'#57dbe42a':'#f66b7a22';c.beginPath();c.arc(a.x,a.y,range,0,7);c.fill();c.strokeStyle=a.type==='player'?'#80f5ff':'#ff8a96';c.stroke()}if(a.power){c.strokeStyle='#ffffff66';for(let i=0;i<8;i++){const ang=rnd(0,7);c.beginPath();c.moveTo(a.x+Math.cos(ang)*range,a.y+Math.sin(ang)*range);c.lineTo(a.x+Math.cos(ang)*40,a.y+Math.sin(ang)*40);c.stroke()}}c.fillStyle=a.type==='player'?'#35d7e1':'#f26672';c.beginPath();c.arc(a.x,a.y,a.r,0,7);c.fill();c.strokeStyle='#182031';c.lineWidth=5;c.stroke();c.save();c.translate(a.x,a.y);c.rotate(a.angle);c.fillStyle='#ffe468';c.fillRect(10,-6,22,12);c.restore();c.fillStyle='#fff';c.font='bold 12px sans-serif';c.textAlign='center';c.fillText(a.type==='player'?'YOU':'NPC',a.x,a.y-35)}
function drawDebug(c){c.fillStyle='#fff';c.textAlign='left';c.font='12px monospace';c.fillText(`FPS ${game.fps.toFixed(0)} NPC箱 ${game.npc.inventory.length}`,8,16);if(game.npc.target){c.strokeStyle='#ff0';c.beginPath();c.moveTo(game.npc.x,game.npc.y);c.lineTo(game.npc.target.x,game.npc.target.y);c.stroke()}c.strokeStyle='#f0f';for(const o of obstacles)c.strokeRect(o.x,o.y,o.w,o.h)}
function pauseToggle(){if(screen!=='game'||!game)return;game.paused=!game.paused;keys.clear();app.querySelector('#pause').innerHTML=game.paused?`<div class="overlay"><section class="panel center"><h1>一時停止</h1><p>WASD / 矢印：移動<br>Space：強力吸引　E：生成</p><button class="primary" data-act="resume">再開</button><button class="secondary" data-act="title">タイトルへ戻る</button></section></div>`:'';last=performance.now()}
function finalSelect(){cancelAnimationFrame(raf);raf=0;screen='final';const p=game.player,n=game.npc;n.choice=n.garage.sort((a,b)=>scoreVehicle(b,target).score-scoreVehicle(a,target).score)[0]||null;const cards=p.garage.map((v,i)=>{const s=scoreVehicle(v,target),c=v.assignments.reduce((o,a)=>(o[a.type]=(o[a.type]||0)+1,o),{});return `<button class="garage-card ${i===0?'selected':''}" data-choice="${i}"><div class="vicon">${VEHICLES[v.base].icon}</div><h3>${v.name}</h3><div class="slots">ベース：${VEHICLES[v.base].name}<br>使用：${v.items.map(x=>x.name).join('、')}<br>正規 ${c.exact||0} / 共通 ${c.common||0} / 代用 ${c.substitute||0} / ガラクタ ${c.junk||0}<br>不足 ${c.missing||0}<br><b>予想 ${s.score}点</b></div></button>`}).join('');app.innerHTML=`<main class="screen"><section class="panel"><h1>勝負する1台を選択</h1>${p.garage.length?`<div class="cards">${cards}</div><div class="center"><button class="primary" data-act="battle">この乗り物で勝負</button></div>`:`<div class="instructions center"><h2>完成車なし</h2><p>あなたの得点は0点です。</p><button class="primary" data-act="battle">結果を見る</button></div>`}</section></main>`;game.choice=p.garage[0]||null}
function result(){screen='result';const ps=scoreVehicle(game.choice,target),ns=scoreVehicle(game.npc.choice,target),out=ps.score>ns.score?'勝利！':ps.score<ns.score?'敗北…':'引き分け',high=Math.max(+localStorage.getItem('grbHigh')||0,ps.score);localStorage.setItem('grbHigh',high);beep(ps.score>=ns.score?'win':'lose');const detail=s=>`正規 ${s.counts.exact} / 共通 ${s.counts.common} / 代用品 ${s.counts.substitute}<br>ガラクタ ${s.counts.junk} / 不足 ${s.counts.missing}<br>ガラクタ度 ${(s.degree*100).toFixed(1)}%`;app.innerHTML=`<main class="screen"><section class="panel center"><h1 class="title">${out}</h1><div class="result-grid"><div class="breakdown"><h2>YOU</h2><div class="vicon">${game.choice?VEHICLES[game.choice.base].icon:'❌'}</div><b>${game.choice?.name||'完成車なし'}</b><div class="score">${ps.score}</div>${detail(ps)}</div><div class="breakdown"><h2>NPC</h2><div class="vicon">${game.npc.choice?VEHICLES[game.npc.choice.base].icon:'❌'}</div><b>${game.npc.choice?.name||'完成車なし'}</b><div class="score">${ns.score}</div>${detail(ns)}</div></div><button class="primary" data-act="again">もう一度遊ぶ</button><button class="secondary" data-act="select">乗り物選択へ戻る</button></section></main>`}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.target){target=b.dataset.target;select();return}const a=b.dataset.act;if(a==='sound'){sound=!sound;localStorage.setItem('grbSound',sound?'on':'off');b.textContent=`🔊 ${sound?'ON':'OFF'}`}if(a==='start'){audio??=new AudioContext();audio.resume();select()}if(a==='round')startGame();if(a==='title')title();if(a==='select')select();if(a==='again')startGame();if(a==='resume')pauseToggle();if(a==='battle')result();if(b.dataset.choice!=null){game.choice=game.player.garage[+b.dataset.choice];document.querySelectorAll('.garage-card').forEach(x=>x.classList.toggle('selected',x===b))}});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape'&&!e.repeat)pauseToggle();if(k==='e'&&!e.repeat&&screen==='game')build(game.player);keys.add(k);if(k===' '&&!e.repeat&&screen==='game')beep('power')});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(screen==='game'&&game&&!game.paused)pauseToggle()});
title();
