import './style.css';import {CONFIG,VEHICLES,VEHICLE_ORDER,SUBSTITUTES,JUNK,SIZE,MIN_PARTS,meta,slotList} from './data.js';import {buildVehicle,scoreVehicle,removeUsed,relation,findBestVehicle,addToInventory} from './logic.js';
const app=document.querySelector('#app'),debug=new URLSearchParams(location.search).get('debug')==='1';
let screen='title',sound=localStorage.getItem('grbSound')!=='off',audio=null,game=null,raf=0,keys=new Set(),last=0,uid=0;const arenaImage=new Image();arenaImage.src='/assets/junkyard-arena.png';
const obstacles=[{x:270,y:100,w:85,h:45,c:'#8e6548',t:'机'},{x:510,y:90,w:60,h:90,c:'#7b563e',t:'箱'},{x:385,y:320,w:120,h:42,c:'#846044',t:'机'},{x:710,y:255,w:62,h:65,c:'#72513c',t:'箱'},{x:150,y:340,w:25,h:35,c:'#f07834',t:'△'},{x:820,y:110,w:25,h:35,c:'#f07834',t:'△'}];
function beep(kind){if(!sound||!audio)return;const map={collect:[650,.05],power:[180,.12],build:[330,.35],warn:[880,.12],win:[520,.5],lose:[130,.45]};const [f,d]=map[kind]||map.collect,o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type=kind==='build'?'square':'sine';g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function soundButton(){return `<button class="secondary sound" data-act="sound">🔊 ${sound?'ON':'OFF'}</button>`}
function title(){stop();screen='title';app.innerHTML=`${soundButton()}<main class="screen"><section class="panel center"><h1 class="title">ガラクタ・ルンバ<br>ビルダーズ</h1><p class="subtitle">30秒で部品を選んで吸い込み、最高の乗り物を作ろう！</p><button class="primary" data-act="start">すぐに回収開始</button><div class="instructions"><b>操作方法</b><br>WASD / 矢印：移動（近くの部品を自動吸引）<br>E：予想表示中の乗り物を生成　 Esc：一時停止</div><p>🏆 最高得点：<b>${localStorage.getItem('grbHigh')||0}</b> / 1000</p></section></main>`}
function rnd(a,b){return a+Math.random()*(b-a)}function hitsRect(x,y,r,o){return x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h}function freePos(near){for(let z=0;z<100;z++){let x=near?rnd(near.x-100,near.x+100):rnd(35,925),y=near?rnd(near.y-100,near.y+100):rnd(45,495);if(x>25&&x<935&&y>30&&y<510&&!obstacles.some(o=>hitsRect(x,y,20,o)))return{x,y}}return{x:480,y:270}}
function makeItem(name,near){const m=meta(name),p=freePos(near);return{id:'i'+uid++,name,...m,...SIZE[m.size],x:p.x,y:p.y,vx:0,vy:0,progressP:0,progressN:0}}
function itemPool(){let names=[];for(const k of VEHICLE_ORDER)names.push(...slotList(k));const all=VEHICLE_ORDER.flatMap(slotList),subs=Object.keys(SUBSTITUTES);while(names.length<55)names.push(all[Math.floor(Math.random()*all.length)]);while(names.length<72)names.push(subs[Math.floor(Math.random()*subs.length)]);while(names.length<80)names.push(JUNK[Math.floor(Math.random()*JUNK.length)]);return names.sort(()=>Math.random()-.5).map((n,i)=>makeItem(n,i<5?{x:100,y:270}:i<10?{x:860,y:270}:null))}
function startGame(){screen='game';keys.clear();const now=performance.now();game={time:CONFIG.ROUND,player:actor(90,270,'player'),npc:actor(870,270,'npc'),items:itemPool(),respawns:[],particles:[],message:'部品を選んで集めよう！',messageT:1.5,paused:false,warn10:false,warn5:false,shake:0,buildCd:0,npcThink:0,fps:60};renderShell();last=now;cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function actor(x,y,type){return{x,y,r:27,type,angle:0,inventory:[],garage:[],target:null}}
function renderShell(){app.innerHTML=`<div class="game-shell"><div class="hud"><span>⏱ <b id="time">30.0</b>秒</span><span>吸引 <b>通常のみ</b></span><span>YOU <b id="pc">0 / 25</b>　完成 <b id="pg">0</b></span><span>NPC <b id="nc">0 / 25</b>　完成 <b id="ng">0</b></span></div><div class="stage-wrap"><canvas class="stage"></canvas><aside class="inventory"><h3>回収ボックス</h3><div id="inv"></div></aside><div class="message" id="msg"></div><div id="pause"></div></div><div class="bottom"><div class="build-hint" id="hint">予想：あと5個</div><div class="garage" id="garage"></div><span>回収品は5秒後に復活</span></div></div>`;const c=app.querySelector('canvas');c.width=CONFIG.W*devicePixelRatio;c.height=CONFIG.H*devicePixelRatio;c.getContext('2d').scale(devicePixelRatio,devicePixelRatio);game.canvas=c;game.ctx=c.getContext('2d')}
function stop(){cancelAnimationFrame(raf);raf=0;keys.clear();game=null}
function moveActor(a,dx,dy,speed,dt){const l=Math.hypot(dx,dy)||1,ox=a.x,oy=a.y;a.x+=dx/l*speed*dt;a.y+=dy/l*speed*dt;a.x=Math.max(a.r,Math.min(CONFIG.W-a.r,a.x));a.y=Math.max(a.r,Math.min(CONFIG.H-a.r,a.y));if(obstacles.some(o=>hitsRect(a.x,a.y,a.r,o))){a.x=ox;if(obstacles.some(o=>hitsRect(a.x,a.y,a.r,o)))a.y=oy}if(dx||dy)a.angle=Math.atan2(dy,dx)}
function suck(a,item,dt){const range=CONFIG.NORMAL_RANGE,d=Math.hypot(item.x-a.x,item.y-a.y);if(d>range)return;const force=105*(1-d/range),ox=item.x,oy=item.y;item.x+=(a.x-item.x)/(d||1)*force*dt;item.y+=(a.y-item.y)/(d||1)*force*dt;if(obstacles.some(o=>hitsRect(item.x,item.y,item.r,o))){item.x=ox;item.y=oy}const key=a.type==='player'?'progressP':'progressN';if(d<a.r+item.r+9)item[key]+=dt;else item[key]=Math.max(0,item[key]-dt*.4);if(item[key]>=item.time)collect(a,item)}
function collect(a,item){if(a.inventory.length>=CONFIG.CAPACITY){if(a.type==='player')say('回収ボックス満杯！');item.progressP=item.progressN=0;return}a.inventory=addToInventory(a.inventory,item,CONFIG.CAPACITY);game.items=game.items.filter(x=>x!==item);game.respawns.push({name:item.name,time:CONFIG.RESPAWN});burst(item.x,item.y,item.color,6);if(a.type==='player'){beep('collect');say('部品を回収！',.35)}}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)game.particles.push({x,y,vx:rnd(-80,80),vy:rnd(-90,40),life:rnd(.3,.7),color})}
function say(s,t=1.1){if(!game)return;game.message=s;game.messageT=t}
function build(a){if(game.paused||game.buildCd>0)return;const predicted=findBestVehicle(a.inventory);if(!predicted){if(a.type==='player')say('生成には最低5個必要です');return}const v=buildVehicle(a.inventory);if(!v)return;a.inventory=removeUsed(a.inventory,v.usedIds);a.garage.push(v);game.buildCd=.42;game.shake=.35;burst(a.x,a.y,'#fff',22);burst(a.x,a.y,'#ffdc62',12);beep('build');say(`${v.name}が完成！`,1.5)}
function npcAI(dt){const n=game.npc;n.npcThink-=dt;if(n.npcThink<=0||!n.target||!game.items.includes(n.target)){n.npcThink=rnd(.12,.3);n.target=[...game.items].sort((a,b)=>npcValue(b,n)-npcValue(a,n))[0]}const predicted=findBestVehicle(n.inventory);if(n.inventory.length>=16||(game.time<=6&&predicted)||(predicted&&predicted.rate>=78))build(n);if(n.target){const wobble=Math.sin(performance.now()/300)*.18,dx=n.target.x-n.x,dy=n.target.y-n.y;moveActor(n,dx+Math.cos(wobble)*18,dy+Math.sin(wobble)*18,225,dt)}}
function npcValue(i,n){const d=Math.hypot(i.x-n.x,i.y-n.y);let q=0;for(const k of VEHICLE_ORDER)for(const s of slotList(k))q=Math.max(q,relation(i,s).value);return q*2.2-d+rnd(0,35)}
function update(dt){if(game.paused)return;game.time=Math.max(0,game.time-dt);game.buildCd=Math.max(0,game.buildCd-dt);game.shake=Math.max(0,game.shake-dt);game.messageT=Math.max(0,game.messageT-dt);const p=game.player,dx=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft')),dy=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));moveActor(p,dx,dy,CONFIG.PLAYER_SPEED,dt);npcAI(dt);for(const i of [...game.items]){suck(p,i,dt);if(game.items.includes(i))suck(game.npc,i,dt)}for(const r of game.respawns)r.time-=dt;for(const r of game.respawns.filter(r=>r.time<=0))game.items.push(makeItem(r.name));game.respawns=game.respawns.filter(r=>r.time>0);for(const q of game.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=110*dt;q.life-=dt}game.particles=game.particles.filter(q=>q.life>0);if(game.time<=10&&!game.warn10){game.warn10=true;beep('warn');say('残り10秒！')}if(game.time<=5&&!game.warn5){game.warn5=true;beep('warn');say('残り5秒！')}if(game.time<=0){if(findBestVehicle(game.npc.inventory))build(game.npc);finishRound();return}updateHud()}
function updateHud(){const g=game,p=g.player,n=g.npc,pred=findBestVehicle(p.inventory);app.querySelector('#time').textContent=g.time.toFixed(1);app.querySelector('#pc').textContent=`${p.inventory.length} / 25`;app.querySelector('#nc').textContent=`${n.inventory.length} / 25`;app.querySelector('#pg').textContent=p.garage.length;app.querySelector('#ng').textContent=n.garage.length;const counts={};p.inventory.forEach(i=>counts[i.name]=(counts[i.name]||0)+1);app.querySelector('#inv').innerHTML=Object.entries(counts).map(([x,c])=>`<div class="item-row"><span>${x}</span><b>× ${c}</b></div>`).join('')||'空っぽ';app.querySelector('#hint').innerHTML=pred?`✅ 予想 ${VEHICLES[pred.key].icon} ${VEHICLES[pred.key].name}<br>完成度 ${pred.rate.toFixed(0)}%　E：生成`:`🔒 予想判定まであと ${5-p.inventory.length}個`;app.querySelector('#garage').innerHTML=p.garage.map(v=>`<div class="mini">${VEHICLES[v.base].icon} ${v.name}<br>${scoreVehicle(v,v.base).score}点</div>`).join('');app.querySelector('#msg').textContent=g.messageT>0?g.message:''}
function loop(t){if(!game)return;let dt=Math.min(.033,(t-last)/1000);last=t;game.fps=game.fps*.9+(1/dt)*.1;update(dt);if(!game)return;draw();raf=requestAnimationFrame(loop)}
function draw(){const {ctx}=game;ctx.save();if(game.shake)ctx.translate(rnd(-5,5),rnd(-5,5));if(arenaImage.complete&&arenaImage.naturalWidth)ctx.drawImage(arenaImage,0,0,960,540);else{ctx.fillStyle='#556b48';ctx.fillRect(0,0,960,540)}for(const o of obstacles){ctx.fillStyle=o.c;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText(o.t,o.x+5,o.y+17)}for(const i of game.items)drawItem(ctx,i);drawActor(ctx,game.player);drawActor(ctx,game.npc);for(const p of game.particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5)}ctx.globalAlpha=1;if(debug)drawDebug(ctx);ctx.restore()}
function drawItem(c,i){c.save();c.translate(i.x,i.y);c.fillStyle=i.color;c.strokeStyle='#18202b';c.lineWidth=3;if(['タイヤ','車輪','ドーナツ','クッキー'].includes(i.name)){c.beginPath();c.arc(0,0,i.r,0,7);c.fill();c.stroke();if(i.name!=='クッキー'){c.fillStyle='#556b48';c.beginPath();c.arc(0,0,i.r*.42,0,7);c.fill()}}else if(i.name==='主翼'||i.name==='尾翼'||i.name==='段ボール'||i.name==='スキー板'){c.fillRect(-i.r,-i.r*.35,i.r*2,i.r*.7)}else{c.fillRect(-i.r,-i.r,i.r*2,i.r*2);c.strokeRect(-i.r,-i.r,i.r*2,i.r*2)}c.fillStyle=i.name==='冷蔵庫'?'#222':'#fff';c.textAlign='center';c.font='bold 10px sans-serif';c.fillText(i.label,0,3);c.restore();const pr=Math.max(i.progressP,i.progressN)/i.time;if(pr>0){c.fillStyle='#222';c.fillRect(i.x-15,i.y-i.r-8,30,4);c.fillStyle='#ffdf55';c.fillRect(i.x-15,i.y-i.r-8,30*Math.min(1,pr),4)}}
function drawActor(c,a){if(debug){c.fillStyle=a.type==='player'?'#57dbe42a':'#f66b7a22';c.beginPath();c.arc(a.x,a.y,CONFIG.NORMAL_RANGE,0,7);c.fill();c.strokeStyle=a.type==='player'?'#80f5ff':'#ff8a96';c.stroke()}c.fillStyle=a.type==='player'?'#35d7e1':'#f26672';c.beginPath();c.arc(a.x,a.y,a.r,0,7);c.fill();c.strokeStyle='#182031';c.lineWidth=5;c.stroke();c.save();c.translate(a.x,a.y);c.rotate(a.angle);c.fillStyle='#ffe468';c.fillRect(10,-6,22,12);c.restore();c.fillStyle='#fff';c.font='bold 12px sans-serif';c.textAlign='center';c.fillText(a.type==='player'?'YOU':'NPC',a.x,a.y-35)}
function drawDebug(c){c.fillStyle='#fff';c.textAlign='left';c.font='12px monospace';c.fillText(`FPS ${game.fps.toFixed(0)} NPC箱 ${game.npc.inventory.length}`,8,16);if(game.npc.target){c.strokeStyle='#ff0';c.beginPath();c.moveTo(game.npc.x,game.npc.y);c.lineTo(game.npc.target.x,game.npc.target.y);c.stroke()}c.strokeStyle='#f0f';for(const o of obstacles)c.strokeRect(o.x,o.y,o.w,o.h)}
function pauseToggle(){if(screen!=='game'||!game)return;game.paused=!game.paused;keys.clear();app.querySelector('#pause').innerHTML=game.paused?`<div class="overlay"><section class="panel center"><h1>一時停止</h1><p>WASD / 矢印：移動<br>近くの部品を自動吸引　E：生成</p><button class="primary" data-act="resume">再開</button><button class="secondary" data-act="title">タイトルへ戻る</button></section></div>`:'';last=performance.now()}
function vehicleRank(v){const s=scoreVehicle(v,v?.base);return {v,s,exact:s.counts.exact,junk:s.counts.junk,used:v?.items.length||0}}
function compareVehicles(a,b){const x=vehicleRank(a),y=vehicleRank(b);return y.s.score-x.s.score||y.exact-x.exact||x.junk-y.junk||y.used-x.used}
function compareChoices(a,b){const x=vehicleRank(a),y=vehicleRank(b);return x.s.score-y.s.score||x.exact-y.exact||y.junk-x.junk||x.used-y.used}
function finishRound(){cancelAnimationFrame(raf);raf=0;game.choice=[...game.player.garage].sort(compareVehicles)[0]||null;game.npc.choice=[...game.npc.garage].sort(compareVehicles)[0]||null;result()}
function result(){screen='result';const ps=scoreVehicle(game.choice,game.choice?.base||'car'),ns=scoreVehicle(game.npc.choice,game.npc.choice?.base||'car'),cmp=compareChoices(game.choice,game.npc.choice),out=cmp>0?'勝利！':cmp<0?'敗北…':'引き分け',high=Math.max(+localStorage.getItem('grbHigh')||0,ps.score);localStorage.setItem('grbHigh',high);beep(cmp>=0?'win':'lose');const detail=s=>`正規 ${s.counts.exact} / 共通 ${s.counts.common} / 代用品 ${s.counts.substitute}<br>ガラクタ ${s.counts.junk} / 不足 ${s.counts.missing}<br>ガラクタ度 ${(s.degree*100).toFixed(1)}%`;app.innerHTML=`<main class="screen"><section class="panel center"><h1 class="title">${out}</h1><p>各自の最高車両を、その車両自身の設計図で採点</p><div class="result-grid"><div class="breakdown"><h2>YOU（${game.player.garage.length}台）</h2><div class="vicon">${game.choice?VEHICLES[game.choice.base].icon:'❌'}</div><b>${game.choice?.name||'完成車なし'}</b><div class="score">${ps.score}</div>${detail(ps)}<br>使用部品 ${game.choice?.items.length||0}</div><div class="breakdown"><h2>NPC（${game.npc.garage.length}台）</h2><div class="vicon">${game.npc.choice?VEHICLES[game.npc.choice.base].icon:'❌'}</div><b>${game.npc.choice?.name||'完成車なし'}</b><div class="score">${ns.score}</div>${detail(ns)}<br>使用部品 ${game.npc.choice?.items.length||0}</div></div><p>同点判定：正規部品数 → ガラクタの少なさ → 使用部品数</p><button class="primary" data-act="again">もう一度遊ぶ</button><button class="secondary" data-act="title">タイトルへ戻る</button></section></main>`}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.act;if(a==='sound'){sound=!sound;localStorage.setItem('grbSound',sound?'on':'off');b.textContent=`🔊 ${sound?'ON':'OFF'}`}if(a==='start'){audio??=new AudioContext();audio.resume();startGame()}if(a==='title')title();if(a==='again')startGame();if(a==='resume')pauseToggle()});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape'&&!e.repeat)pauseToggle();if(k==='e'&&!e.repeat&&screen==='game')build(game.player);keys.add(k)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(screen==='game'&&game&&!game.paused)pauseToggle()});
title();
